### ISSUE TITLE
help

### ISSUE THREAD

**Issue by billyrudi** [scanf6/pdfmake-to-excel#2]
TypeError: ExcelConverter is not a function at downloadFile (/Users/paololops/pdfmake/examples/tables.js:259:16) at creareport (/Users/paololops/pdfmake/examples/tables.js:268:2) at /Users/paololops/pdfmake/examples/tables.js:154:5 at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async estraitutti (/Users/paololops/pdfmake/examples/tables.js:143:2) {stack: "TypeError: ExcelConverter is not a function\n at…Users/paololops/pdfmake/examples/tables.js:143:2)", message: "ExcelConverter is not a function"}

**Comment by scanf6** [comment]
Hi @billyrudi , could you provide the code, and if possible the payload of your docDefinition so I can reproduce the issue please ?

**Comment by billyrudi** [comment]
hi, yes 
`var  ExcelConverter = require( 'pdfmake-to-excel');

var dd = {
		pageOrientation: 'landscape',
		//watermark: { text: 'test watermark', fontSize: 20 },
		footer:  function(currentPage, pageCount) { return currentPage.toString() + ' of ' + pageCount + ' ' + new Date().toDateString();},
		content: [
			{text: 'Flowers report colli mancanti ' + new Date().toDateString() + ' ' + new Date().toLocaleTimeString(), style: 'header'},
			{
				style: 'tableExample',
				table: {
					widths: ['auto', 'auto','auto', 'auto','auto', 'auto','auto', 'auto', 'auto','auto', 'auto','auto', 'auto'],
					body: rows,
					headerRows: 1
				}
			},

		],

		styles: {
			header: {
				fontSize: 18,
				bold: true,
				margin: [0, 0, 0, 0]
			},
			subheader: {
				fontSize: 16,
				bold: true,
				margin: [0, 0, 0, 0]
			},
			tableExample: {
				margin: [0, 0, 0, 0]
			},
			tableHeader: {
				bold: true,
				fontSize: 9,
				color: 'black'
			}
		},
		defaultStyle: {
			// alignment: 'justify'
		}

	}

function downloadFile() {
    const exporter = new ExcelConverter(
        'Test',
        dd,
        {
            defaultOptions: {defaultColWidth: 20}
        }
    );
    exporter.downloadExcel();
}`

**Comment by scanf6** [comment]
Ok good. ExcelConverter is not a default export, but a named one. 

Can you try to import it like this:
`import {ExcelConverter} from 'pdfmake-to-excel';`

Or if you can't use the module imports, try like this:
`const {ExcelConverter} = require('pdfmake-to-excel');`

**Comment by billyrudi** [comment]
OK, now i have:
Uncaught ReferenceError: Blob is not defined
(anonymous function)	converter.js:91

**Comment by billyrudi** [comment]
hi, do you have news?

**Comment by scanf6** [comment]
Hi @billyrudi , sorry for the late responses. Please are you trying to use the package on the backend with the streams or on the frontend ?

**Comment by billyrudi** [comment]
Hi, I i don't understand... I'm using it within a pdfmake example folder

**Comment by scanf6** [comment]
Just a reminder that you don't need pdfmake to use this library. Are you using the package in a node application ? React, Vue. Can you give a link to a repository maybe ?

**Comment by billyrudi** [comment]
i use react. i have sent you entire project. i use node tables.js to start it

**Comment by scanf6** [comment]
Hey @billyrudi , I did not receive your project. Please contact me at scanf555@gmail.com you we can look into it

**Comment by newmesiss** [comment]
esto aun funciona?
